run:
  run_id: proposed-DistilBERT-base-66M-CIFAR-10
  method: proposed
  model:
    name: distilbert-base-uncased
    task_adapters:
      enabled: true
      adapter_type: houlsby
      reduction_factor: 16
      non_linearity: relu
    num_labels: 10
    input_representation: image_sequence
    vision_patch:
      patch_size: 4
  dataset:
    name: cifar10
    split:
      train: 0.8
      val: 0.1
      test: 0.1
    preprocessing:
      resize: 32
      augmentations:
      - random_crop
      - horizontal_flip
  training:
    optimizer: adamw
    learning_rate: 0.0001
    batch_size: 16
    epochs: 20
    weight_decay: 0.01
    warmup_steps: 500
    max_grad_norm: 1.0
    gradient_accumulation_steps: 1
  evaluation:
    metrics:
    - accuracy
    - f1_score
    - inference_time
  optuna:
    n_trials: 25
    direction: maximize
    search_space:
      learning_rate:
        type: loguniform
        low: 1.0e-05
        high: 0.0005
      batch_size:
        type: categorical
        choices:
        - 8
        - 16
        - 32
      adapter_reduction_factor:
        type: int
        low: 4
        high: 32
        step: 4
      weight_decay:
        type: uniform
        low: 0.0
        high: 0.1
wandb:
  entity: gengaru617-personal
  project: 251017-test
  mode: disabled
trial_mode: true
results_dir: .research/iteration1
run_id: proposed-DistilBERT-base-66M-CIFAR-10
method: proposed
model:
  name: distilbert-base-uncased
  task_adapters:
    enabled: true
    adapter_type: houlsby
    reduction_factor: 16
    non_linearity: relu
  num_labels: 10
  input_representation: image_sequence
  vision_patch:
    patch_size: 4
dataset:
  name: cifar10
  split:
    train: 0.8
    val: 0.1
    test: 0.1
  preprocessing:
    resize: 32
    augmentations:
    - random_crop
    - horizontal_flip
training:
  optimizer: adamw
  learning_rate: 0.0001
  batch_size: 16
  epochs: 20
  weight_decay: 0.01
  warmup_steps: 500
  max_grad_norm: 1.0
  gradient_accumulation_steps: 1
evaluation:
  metrics:
  - accuracy
  - f1_score
  - inference_time
optuna:
  n_trials: 25
  direction: maximize
  search_space:
    learning_rate:
      type: loguniform
      low: 1.0e-05
      high: 0.0005
    batch_size:
      type: categorical
      choices:
      - 8
      - 16
      - 32
    adapter_reduction_factor:
      type: int
      low: 4
      high: 32
      step: 4
    weight_decay:
      type: uniform
      low: 0.0
      high: 0.1
